### PR TITLE
Adding azimuth carrier computation for bursts

### PR DESCRIPTION
**Pull request by vbrancat**
This PR adds the functionality of computing the azimuth carrier polynomials to the S1 reader for each burst (if requested).

This functionality will be needed for both COMPASS range/Doppler and geocoded CSLC workflow. To avoid code duplication, it makes sense that this functionality sits in the reader.

Note: the `polyfit` function in `sentinel1_burst_slc.py `needs help for the documentation.

### CODE REVIEW

**Review by hfattahi — APPROVED** [review]
Thanks @vbrancat for pushing this part of the reader.

**Comment by LiangJYu** [comment]
LGTM. Just address Codacy warnings.

**Comment by yunjunz** [comment]
The `datetime` module is imported twice in the code with different styles, would recommend unifying them, such as below at the top of the script:

```python
import datetime as dt
```

@LiangJYu We has similar syle inconsistency of `datetime` in `sentinel1_orbit_reader.py` and `sentinel1_reader.py` as well, might be a good idea to use the same import style as above as well?

**Comment by vbrancat** [comment]
@LiangJYu did my best to address codacy issues. There is only one remaining related to an unused (but in reality is used) variable. @yunjunz you are right. Our imports of the `datetime` module are ambiguous. However, we cannot use your suggestion (`import datetime as dt`) as we use `dt` in to indicate a time difference. I decided to resolve the issue you pointed out using `import datetime as datetime`. It is a bit long but rather straightforward and unambiguous and it also help code readability. Waiting for your green light to merge the PR.

**Review by yunjunz — APPROVED** [review]
Looks great to me!

**Pull request merged**
